# Generated by Django 3.1.1 on 2021-07-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='imagen', upload_to='imagenes/'),
        ),
    ]
